[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "rl_trading"
version = "0.0.1"
description = "Reinforcement Learning Algorithm for trading"
authors = [
    {name = "Ivan Kolesnikov", email = "ivan_kolesnikov@yahoo.com"}
]
readme = "README.md"
requires-python = ">=3.12, <=3.13"
dependencies = [
    "pandas>=2.3.3",
    "numpy>=2.2.6",
    "lz4==4.4.5",
    "torch>=2.7.0",
    "ray==2.52.1",
    "gymnasium>=1.2.2",
    "pandas-ta==0.4.71b0",
    "gputil>=1.4.0",
    "dill>=0.3.8"
]

[project.optional-dependencies]
test = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "pytest-xdist>=3.6.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["rl_trading"]
exclude = ["tests*", "notebooks*", "data*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

[tool.coverage.run]
source = ["rl_trading"]
omit = [
    "*/tests/*",
    "*/test_*.py",
    "*/__pycache__/*",
    "*/setup.py",
    "*/conftest.py",
]
branch = true
